name: sweetxeet
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_appauth: ^8.0.3
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.0.6
  http: ^1.1.0
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

module:
    androidX: true # Add this line.